import mongoose from "mongoose";
import dotenv from "dotenv";
import { Ingredient } from "../models/Ingredient.js";
import { IngredientAlias } from "../models/IngredientAlias.js";

dotenv.config();

const DEFAULT_URI = "mongodb://127.0.0.1:27017/nhahang";
const uri = process.env.MONGODB_URI || DEFAULT_URI;

interface SeedIngredientInput {
  name: string;
  slug: string;
  category: string;
  defaultUnit: 'g' | 'ml' | 'piece';
  gramsPerUnit: number;
  caloriesPer100g: number;
  proteinPer100g: number;
  carbPer100g: number;
  fatPer100g: number;
  fiberPer100g: number;
  sugarPer100g: number;
  sodiumPer100g: number;
  allergens: string[];
  aliases: Array<{ alias: string; language: 'vi' | 'en' }>;
}

const seedData: SeedIngredientInput[] = [
  // ══ PROTEIN ══════════════════════════════════════════════════════════
  {
    name: "Ức gà",
    slug: "uc-ga",
    category: "protein",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 165,
    proteinPer100g: 31,
    carbPer100g: 0,
    fatPer100g: 3.6,
    fiberPer100g: 0,
    sugarPer100g: 0,
    sodiumPer100g: 74,
    allergens: [],
    aliases: [
      { alias: "ức gà", language: "vi" },
      { alias: "lườn gà", language: "vi" },
      { alias: "uc ga", language: "vi" },
      { alias: "ga", language: "vi" },
      { alias: "chicken breast", language: "en" },
    ],
  },
  {
    name: "Thịt bò",
    slug: "thit-bo",
    category: "protein",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 250,
    proteinPer100g: 26,
    carbPer100g: 0,
    fatPer100g: 15,
    fiberPer100g: 0,
    sugarPer100g: 0,
    sodiumPer100g: 72,
    allergens: [],
    aliases: [
      { alias: "thịt bò", language: "vi" },
      { alias: "bò", language: "vi" },
      { alias: "thit bo", language: "vi" },
      { alias: "bo", language: "vi" },
      { alias: "beef", language: "en" },
    ],
  },
  {
    name: "Thịt heo",
    slug: "thit-heo",
    category: "protein",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 242,
    proteinPer100g: 27,
    carbPer100g: 0,
    fatPer100g: 14,
    fiberPer100g: 0,
    sugarPer100g: 0,
    sodiumPer100g: 62,
    allergens: [],
    aliases: [
      { alias: "thịt heo", language: "vi" },
      { alias: "thịt lợn", language: "vi" },
      { alias: "heo", language: "vi" },
      { alias: "thit heo", language: "vi" },
      { alias: "pork", language: "en" },
    ],
  },
  {
    name: "Cá hồi",
    slug: "ca-hoi",
    category: "protein",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 208,
    proteinPer100g: 20,
    carbPer100g: 0,
    fatPer100g: 13,
    fiberPer100g: 0,
    sugarPer100g: 0,
    sodiumPer100g: 59,
    allergens: ["fish"],
    aliases: [
      { alias: "cá hồi", language: "vi" },
      { alias: "ca hoi", language: "vi" },
      { alias: "salmon", language: "en" },
    ],
  },
  {
    name: "Trứng gà",
    slug: "trung-ga",
    category: "protein",
    defaultUnit: "piece",
    gramsPerUnit: 50,
    caloriesPer100g: 155,
    proteinPer100g: 13,
    carbPer100g: 1.1,
    fatPer100g: 11,
    fiberPer100g: 0,
    sugarPer100g: 1.1,
    sodiumPer100g: 124,
    allergens: ["eggs"],
    aliases: [
      { alias: "trứng gà", language: "vi" },
      { alias: "trứng", language: "vi" },
      { alias: "trung ga", language: "vi" },
      { alias: "quả trứng", language: "vi" },
      { alias: "egg", language: "en" },
    ],
  },
  {
    name: "Đậu hũ",
    slug: "dau-hu",
    category: "protein",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 76,
    proteinPer100g: 8,
    carbPer100g: 1.9,
    fatPer100g: 4.8,
    fiberPer100g: 0.3,
    sugarPer100g: 0,
    sodiumPer100g: 7,
    allergens: ["soy"],
    aliases: [
      { alias: "đậu hũ", language: "vi" },
      { alias: "đậu phụ", language: "vi" },
      { alias: "dau hu", language: "vi" },
      { alias: "tofu", language: "en" },
    ],
  },
  {
    name: "Tôm",
    slug: "tom",
    category: "protein",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 85,
    proteinPer100g: 20,
    carbPer100g: 0,
    fatPer100g: 0.5,
    fiberPer100g: 0,
    sugarPer100g: 0,
    sodiumPer100g: 566,
    allergens: ["shellfish"],
    aliases: [
      { alias: "tôm", language: "vi" },
      { alias: "tom", language: "vi" },
      { alias: "shrimp", language: "en" },
    ],
  },
  {
    name: "Cá basa",
    slug: "ca-basa",
    category: "protein",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 90,
    proteinPer100g: 17,
    carbPer100g: 0,
    fatPer100g: 2.5,
    fiberPer100g: 0,
    sugarPer100g: 0,
    sodiumPer100g: 65,
    allergens: ["fish"],
    aliases: [
      { alias: "cá basa", language: "vi" },
      { alias: "ca basa", language: "vi" },
      { alias: "cá tra", language: "vi" },
      { alias: "basa fish", language: "en" },
    ],
  },

  // ══ TINH BỘT ════════════════════════════════════════════════════════
  {
    name: "Cơm trắng",
    slug: "com-trang",
    category: "tinh_bot",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 130,
    proteinPer100g: 2.7,
    carbPer100g: 28,
    fatPer100g: 0.3,
    fiberPer100g: 0.4,
    sugarPer100g: 0.1,
    sodiumPer100g: 1,
    allergens: [],
    aliases: [
      { alias: "cơm trắng", language: "vi" },
      { alias: "gạo trắng", language: "vi" },
      { alias: "cơm", language: "vi" },
      { alias: "com trang", language: "vi" },
      { alias: "white rice", language: "en" },
    ],
  },
  {
    name: "Gạo lứt",
    slug: "gao-lut",
    category: "tinh_bot",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 111,
    proteinPer100g: 2.6,
    carbPer100g: 23,
    fatPer100g: 0.9,
    fiberPer100g: 1.8,
    sugarPer100g: 0.4,
    sodiumPer100g: 5,
    allergens: [],
    aliases: [
      { alias: "cơm lứt", language: "vi" },
      { alias: "gạo lứt", language: "vi" },
      { alias: "com lut", language: "vi" },
      { alias: "brown rice", language: "en" },
    ],
  },
  {
    name: "Yến mạch",
    slug: "yen-mach",
    category: "tinh_bot",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 389,
    proteinPer100g: 16.9,
    carbPer100g: 66,
    fatPer100g: 6.9,
    fiberPer100g: 10.6,
    sugarPer100g: 0,
    sodiumPer100g: 2,
    allergens: ["gluten"],
    aliases: [
      { alias: "yến mạch", language: "vi" },
      { alias: "yen mach", language: "vi" },
      { alias: "oats", language: "en" },
    ],
  },
  {
    name: "Bột mì",
    slug: "bot-mi",
    category: "tinh_bot",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 364,
    proteinPer100g: 10,
    carbPer100g: 76,
    fatPer100g: 1,
    fiberPer100g: 2.7,
    sugarPer100g: 0.3,
    sodiumPer100g: 2,
    allergens: ["gluten"],
    aliases: [
      { alias: "bột mì", language: "vi" },
      { alias: "bot mi", language: "vi" },
      { alias: "wheat flour", language: "en" },
    ],
  },
  {
    name: "Khoai tây",
    slug: "khoai-tay",
    category: "tinh_bot",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 77,
    proteinPer100g: 2,
    carbPer100g: 17,
    fatPer100g: 0.1,
    fiberPer100g: 2.2,
    sugarPer100g: 0.8,
    sodiumPer100g: 6,
    allergens: [],
    aliases: [
      { alias: "khoai tây", language: "vi" },
      { alias: "khoai tay", language: "vi" },
      { alias: "potato", language: "en" },
    ],
  },
  {
    name: "Khoai lang",
    slug: "khoai-lang",
    category: "tinh_bot",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 86,
    proteinPer100g: 1.6,
    carbPer100g: 20,
    fatPer100g: 0.1,
    fiberPer100g: 3,
    sugarPer100g: 4.2,
    sodiumPer100g: 55,
    allergens: [],
    aliases: [
      { alias: "khoai lang", language: "vi" },
      { alias: "sweet potato", language: "en" },
    ],
  },
  {
    name: "Bún tươi",
    slug: "bun-tuoi",
    category: "tinh_bot",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 109,
    proteinPer100g: 2,
    carbPer100g: 25,
    fatPer100g: 0.2,
    fiberPer100g: 1,
    sugarPer100g: 0,
    sodiumPer100g: 182,
    allergens: [],
    aliases: [
      { alias: "bún", language: "vi" },
      { alias: "bún tươi", language: "vi" },
      { alias: "bun tuoi", language: "vi" },
      { alias: "rice noodles", language: "en" },
    ],
  },
  {
    name: "Bánh phở",
    slug: "banh-pho",
    category: "tinh_bot",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 120,
    proteinPer100g: 2.2,
    carbPer100g: 27,
    fatPer100g: 0.2,
    fiberPer100g: 1.2,
    sugarPer100g: 0,
    sodiumPer100g: 120,
    allergens: [],
    aliases: [
      { alias: "phở", language: "vi" },
      { alias: "bánh phở", language: "vi" },
      { alias: "pho", language: "vi" },
      { alias: "flat rice noodles", language: "en" },
    ],
  },

  // ══ CHẤT BÉO ════════════════════════════════════════════════════════
  {
    name: "Dầu ô liu",
    slug: "dau-o-liu",
    category: "chat_beo",
    defaultUnit: "ml",
    gramsPerUnit: 0.92,
    caloriesPer100g: 884,
    proteinPer100g: 0,
    carbPer100g: 0,
    fatPer100g: 100,
    fiberPer100g: 0,
    sugarPer100g: 0,
    sodiumPer100g: 2,
    allergens: [],
    aliases: [
      { alias: "dầu ô liu", language: "vi" },
      { alias: "dau o liu", language: "vi" },
      { alias: "dầu olive", language: "vi" },
      { alias: "olive oil", language: "en" },
    ],
  },
  {
    name: "Bơ lạt",
    slug: "bo-lat",
    category: "chat_beo",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 717,
    proteinPer100g: 0.9,
    carbPer100g: 0.1,
    fatPer100g: 81,
    fiberPer100g: 0,
    sugarPer100g: 0.1,
    sodiumPer100g: 643,
    allergens: ["dairy"],
    aliases: [
      { alias: "bơ", language: "vi" },
      { alias: "bơ lạt", language: "vi" },
      { alias: "bo lat", language: "vi" },
      { alias: "butter", language: "en" },
    ],
  },
  {
    name: "Dầu ăn",
    slug: "dau-an",
    category: "chat_beo",
    defaultUnit: "ml",
    gramsPerUnit: 0.92,
    caloriesPer100g: 884,
    proteinPer100g: 0,
    carbPer100g: 0,
    fatPer100g: 100,
    fiberPer100g: 0,
    sugarPer100g: 0,
    sodiumPer100g: 0,
    allergens: [],
    aliases: [
      { alias: "dầu thực vật", language: "vi" },
      { alias: "dầu ăn", language: "vi" },
      { alias: "dau an", language: "vi" },
      { alias: "vegetable oil", language: "en" },
    ],
  },
  {
    name: "Hạt điều",
    slug: "hat-dieu",
    category: "chat_beo",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 553,
    proteinPer100g: 18,
    carbPer100g: 30,
    fatPer100g: 44,
    fiberPer100g: 3.3,
    sugarPer100g: 5.9,
    sodiumPer100g: 12,
    allergens: ["nuts"],
    aliases: [
      { alias: "hạt điều", language: "vi" },
      { alias: "hat dieu", language: "vi" },
      { alias: "cashews", language: "en" },
    ],
  },
  {
    name: "Đậu phộng",
    slug: "dau-phong",
    category: "chat_beo",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 567,
    proteinPer100g: 25.8,
    carbPer100g: 16.1,
    fatPer100g: 49.2,
    fiberPer100g: 8.5,
    sugarPer100g: 4,
    sodiumPer100g: 18,
    allergens: ["nuts"],
    aliases: [
      { alias: "đậu phộng", language: "vi" },
      { alias: "lạc", language: "vi" },
      { alias: "dau phong", language: "vi" },
      { alias: "peanuts", language: "en" },
    ],
  },

  // ══ RAU CỦ ══════════════════════════════════════════════════════════
  {
    name: "Bông cải xanh",
    slug: "bong-cai-xanh",
    category: "rau_cu",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 34,
    proteinPer100g: 2.8,
    carbPer100g: 7,
    fatPer100g: 0.4,
    fiberPer100g: 2.6,
    sugarPer100g: 1.7,
    sodiumPer100g: 33,
    allergens: [],
    aliases: [
      { alias: "súp lơ xanh", language: "vi" },
      { alias: "bông cải xanh", language: "vi" },
      { alias: "bong cai xanh", language: "vi" },
      { alias: "broccoli", language: "en" },
    ],
  },
  {
    name: "Xà lách",
    slug: "xa-lach",
    category: "rau_cu",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 15,
    proteinPer100g: 1.4,
    carbPer100g: 2.9,
    fatPer100g: 0.2,
    fiberPer100g: 1.3,
    sugarPer100g: 0.8,
    sodiumPer100g: 28,
    allergens: [],
    aliases: [
      { alias: "xà lách", language: "vi" },
      { alias: "rau diếp", language: "vi" },
      { alias: "xa lach", language: "vi" },
      { alias: "lettuce", language: "en" },
    ],
  },
  {
    name: "Cà chua",
    slug: "ca-chua",
    category: "rau_cu",
    defaultUnit: "piece",
    gramsPerUnit: 120,
    caloriesPer100g: 18,
    proteinPer100g: 0.9,
    carbPer100g: 3.9,
    fatPer100g: 0.2,
    fiberPer100g: 1.2,
    sugarPer100g: 2.6,
    sodiumPer100g: 5,
    allergens: [],
    aliases: [
      { alias: "cà chua", language: "vi" },
      { alias: "ca chua", language: "vi" },
      { alias: "tomato", language: "en" },
    ],
  },
  {
    name: "Dưa leo",
    slug: "dua-leo",
    category: "rau_cu",
    defaultUnit: "piece",
    gramsPerUnit: 150,
    caloriesPer100g: 15,
    proteinPer100g: 0.7,
    carbPer100g: 3.6,
    fatPer100g: 0.1,
    fiberPer100g: 0.5,
    sugarPer100g: 1.7,
    sodiumPer100g: 2,
    allergens: [],
    aliases: [
      { alias: "dưa leo", language: "vi" },
      { alias: "dưa chuột", language: "vi" },
      { alias: "dua leo", language: "vi" },
      { alias: "cucumber", language: "en" },
    ],
  },
  {
    name: "Cà rốt",
    slug: "ca-rot",
    category: "rau_cu",
    defaultUnit: "piece",
    gramsPerUnit: 60,
    caloriesPer100g: 41,
    proteinPer100g: 0.9,
    carbPer100g: 10,
    fatPer100g: 0.2,
    fiberPer100g: 2.8,
    sugarPer100g: 4.7,
    sodiumPer100g: 69,
    allergens: [],
    aliases: [
      { alias: "cà rốt", language: "vi" },
      { alias: "ca rot", language: "vi" },
      { alias: "carrot", language: "en" },
    ],
  },
  {
    name: "Hành tây",
    slug: "hanh-tay",
    category: "rau_cu",
    defaultUnit: "piece",
    gramsPerUnit: 110,
    caloriesPer100g: 40,
    proteinPer100g: 1.1,
    carbPer100g: 9.3,
    fatPer100g: 0.1,
    fiberPer100g: 1.7,
    sugarPer100g: 4.2,
    sodiumPer100g: 4,
    allergens: [],
    aliases: [
      { alias: "hành tây", language: "vi" },
      { alias: "hanh tay", language: "vi" },
      { alias: "onion", language: "en" },
    ],
  },
  {
    name: "Rau muống",
    slug: "rau-muong",
    category: "rau_cu",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 19,
    proteinPer100g: 2.6,
    carbPer100g: 3.1,
    fatPer100g: 0.2,
    fiberPer100g: 2.1,
    sugarPer100g: 0,
    sodiumPer100g: 113,
    allergens: [],
    aliases: [
      { alias: "rau muống", language: "vi" },
      { alias: "rau muong", language: "vi" },
      { alias: "morning glory", language: "en" },
    ],
  },

  // ══ GIA VỊ & SỐT ══════════════════════════════════════════════════
  {
    name: "Nước tương",
    slug: "nuoc-tuong",
    category: "gia_vi",
    defaultUnit: "ml",
    gramsPerUnit: 1.15,
    caloriesPer100g: 53,
    proteinPer100g: 8,
    carbPer100g: 4.9,
    fatPer100g: 0.6,
    fiberPer100g: 0.8,
    sugarPer100g: 0.5,
    sodiumPer100g: 5493,
    allergens: ["soy", "gluten"],
    aliases: [
      { alias: "nước tương", language: "vi" },
      { alias: "xì dầu", language: "vi" },
      { alias: "nuoc tuong", language: "vi" },
      { alias: "soy sauce", language: "en" },
    ],
  },
  {
    name: "Nước mắm",
    slug: "nuoc-mam",
    category: "gia_vi",
    defaultUnit: "ml",
    gramsPerUnit: 1.2,
    caloriesPer100g: 35,
    proteinPer100g: 5.1,
    carbPer100g: 3.6,
    fatPer100g: 0,
    fiberPer100g: 0,
    sugarPer100g: 3.6,
    sodiumPer100g: 7851,
    allergens: ["fish"],
    aliases: [
      { alias: "nước mắm", language: "vi" },
      { alias: "nuoc mam", language: "vi" },
      { alias: "fish sauce", language: "en" },
    ],
  },
  {
    name: "Muối",
    slug: "muoi",
    category: "gia_vi",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 0,
    proteinPer100g: 0,
    carbPer100g: 0,
    fatPer100g: 0,
    fiberPer100g: 0,
    sugarPer100g: 0,
    sodiumPer100g: 38758,
    allergens: [],
    aliases: [
      { alias: "muối", language: "vi" },
      { alias: "muoi", language: "vi" },
      { alias: "salt", language: "en" },
    ],
  },
  {
    name: "Đường trắng",
    slug: "duong-trang",
    category: "gia_vi",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 387,
    proteinPer100g: 0,
    carbPer100g: 100,
    fatPer100g: 0,
    fiberPer100g: 0,
    sugarPer100g: 100,
    sodiumPer100g: 1,
    allergens: [],
    aliases: [
      { alias: "đường", language: "vi" },
      { alias: "đường kính", language: "vi" },
      { alias: "duong", language: "vi" },
      { alias: "sugar", language: "en" },
    ],
  },
  {
    name: "Tương ớt",
    slug: "tuong-ot",
    category: "gia_vi",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 120,
    proteinPer100g: 1.5,
    carbPer100g: 28,
    fatPer100g: 0.2,
    fiberPer100g: 1.2,
    sugarPer100g: 24,
    sodiumPer100g: 1540,
    allergens: [],
    aliases: [
      { alias: "tương ớt", language: "vi" },
      { alias: "tuong ot", language: "vi" },
      { alias: "chili sauce", language: "en" },
    ],
  },
  {
    name: "Tỏi",
    slug: "toi",
    category: "gia_vi",
    defaultUnit: "piece",
    gramsPerUnit: 4,
    caloriesPer100g: 149,
    proteinPer100g: 6.4,
    carbPer100g: 33,
    fatPer100g: 0.5,
    fiberPer100g: 2.1,
    sugarPer100g: 1,
    sodiumPer100g: 17,
    allergens: [],
    aliases: [
      { alias: "tỏi", language: "vi" },
      { alias: "toi", language: "vi" },
      { alias: "garlic", language: "en" },
    ],
  },

  // ══ SỮA & DAIRY ══════════════════════════════════════════════════════
  {
    name: "Sữa tươi",
    slug: "sua-tuoi",
    category: "sua",
    defaultUnit: "ml",
    gramsPerUnit: 1.03,
    caloriesPer100g: 61,
    proteinPer100g: 3.2,
    carbPer100g: 4.8,
    fatPer100g: 3.3,
    fiberPer100g: 0,
    sugarPer100g: 5.1,
    sodiumPer100g: 44,
    allergens: ["dairy"],
    aliases: [
      { alias: "sữa tươi", language: "vi" },
      { alias: "sữa", language: "vi" },
      { alias: "sua tuoi", language: "vi" },
      { alias: "whole milk", language: "en" },
    ],
  },
  {
    name: "Phô mai",
    slug: "pho-mai",
    category: "sua",
    defaultUnit: "g",
    gramsPerUnit: 1,
    caloriesPer100g: 403,
    proteinPer100g: 25,
    carbPer100g: 1.3,
    fatPer100g: 33,
    fiberPer100g: 0,
    sugarPer100g: 0.5,
    sodiumPer100g: 621,
    allergens: ["dairy"],
    aliases: [
      { alias: "phô mai", language: "vi" },
      { alias: "pho mai", language: "vi" },
      { alias: "cheese", language: "en" },
    ],
  },
];

// Vietnamese category labels for display
export const CATEGORY_LABELS: Record<string, string> = {
  protein: "🥩 Đạm",
  tinh_bot: "🌾 Tinh bột",
  chat_beo: "🫒 Chất béo",
  rau_cu: "🥦 Rau củ",
  gia_vi: "🧂 Gia vị",
  sua: "🥛 Sữa & Dairy",
};

async function seed() {
  console.log("🌱 Bắt đầu seed dữ liệu nguyên liệu tiếng Việt...");
  try {
    await mongoose.connect(uri);
    console.log("🔌 Kết nối MongoDB thành công.");

    const existingVerified = await Ingredient.find({ isVerified: true });
    const verifiedIds = existingVerified.map((i) => i._id);
    await IngredientAlias.deleteMany({ ingredientId: { $in: verifiedIds } });
    await Ingredient.deleteMany({ isVerified: true });
    console.log("🧹 Đã xóa dữ liệu cũ.");

    let ingredientCount = 0;
    let aliasCount = 0;

    for (const item of seedData) {
      const { aliases, ...ingredientData } = item;

      const newIngredient = await Ingredient.create({
        ...ingredientData,
        isVerified: true,
        restaurantId: null,
        source: "verified_manual",
        isActive: true,
      });
      ingredientCount++;

      const aliasDocs = aliases.map((a) => ({
        ingredientId: newIngredient._id,
        alias: a.alias,
        aliasNormalized: a.alias
          .toLowerCase()
          .trim()
          .normalize("NFD")
          .replace(/[\u0300-\u036f]/g, "")
          .replace(/[^\w\s]/g, ""),
        language: a.language,
      }));

      // Auto-alias: tên chính cũng thành alias
      aliasDocs.push({
        ingredientId: newIngredient._id,
        alias: newIngredient.name.toLowerCase(),
        aliasNormalized: newIngredient.name
          .toLowerCase()
          .normalize("NFD")
          .replace(/[\u0300-\u036f]/g, "")
          .replace(/[^\w\s]/g, ""),
        language: "vi",
      });

      await IngredientAlias.insertMany(aliasDocs);
      aliasCount += aliasDocs.length;
    }

    console.log(`✅ Đã seed ${ingredientCount} nguyên liệu và ${aliasCount} aliases.`);
  } catch (error) {
    console.error("❌ Seeding thất bại:", error);
  } finally {
    await mongoose.disconnect();
    console.log("🔌 Đã ngắt kết nối MongoDB.");
  }
}

seed();
